server:
  port: 2333
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.25.16.208:5432/db_test
    username: jxglpt
    password: jxglpt
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  thymeleaf:
    cache: false
